apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job2
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hi there from job2!"]
      restartPolicy: Never
